apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: 890337545995.dkr.ecr.ap-south-1.amazonaws.com/userservice:latest
        ports:
        - containerPort: 9002
        envFrom:
        - secretRef:
            name: userservice-db-secret

        env:
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
    - port: 9002
      targetPort: 9002
