apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextgen

resources:
  - ../../base
  - namespace.yaml
  - nextgen-ingress.yaml
  - postgres-sealed-secret.yaml
  - authservice-sealed-secret.yaml
