server:
  port: ${SERVER_PORT:9000}

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:9001}

user:
  url: ${USER_SERVICE_URL:http://localhost:9002}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

spring:
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
