---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authservice-secret
  namespace: nextgen
spec:
  encryptedData:
    JWT_SECRET: AgApT5obEMIcy7e98sBltLjzBHuqqOEM5WG1BjyZxpOvIq7D6UgonDJJVLw+nZHiExvt7PYvAXNob1xvdtSbQderD+qFINTuY9BslpXDyPpd83uuDkC2OUcS9M/1QhIl7xC2jbADMoRLlGnFN6TgzKMUdOlATd/Lq8IoXl4DJjZpaxVYioT8satLQ5CwTDJl31cp/l/xpo7vYmdY7QrJk72rhhw1UKdMu1IyjgzFASnmqpNZE/ntX+r/2VakegK01VvQ1FrKicBpgMm3ByeuSojEd1vlnA1rri4aIT0CDf/F4Ew+9dWjtfSGNBd3JSdY+rYcXBSv5ZXAgLnbLpDOsHvLEmOrfqT3jSgXemBXwLncb3pae3fsk514/fpgBkr4kUot6Fo+VvnC9m5iuXd1n/VeZyvJ3TUKPCy6fqbI+/0Rj+aZuhk5R/sk9GbNAM7mo6cZUWz4M9ONlcl5ZY9XeFwawf0JonXdtbIeOfCB1OOVhlMMe+37te1Bzdq1NiCx5Za1+ygDo6FQx09OEk4+lOSDA2CguoUa9CBoQIZvGfssznqOfZrL5DvHKIjZaqvJN/aP0q9fa2DxAXdPn5A6vXhUO8UnlrNU7c0FT2hGTdF2i0J+Cc6/5vKxa6CFP5VW9SKiLmzrWtZki7yDJTP2OiNX11aneBR3/hELuTLxLYctcM+kBT+Ym/7wRrllfox3wcblYZG1KtXAnxI40T8v3Zzm41dPGCnn7atU9S++Gl7bObnXuvGeDjWr+XvHfg==
    USER_SERVICE_URL: AgBTugLnL533iwNcZLMqRqgRanT7UMxBX/k3ULhASyyxBrsbtVHDdGQJhKIvaMBTyw/U1Hnl9GBbMYZg5TttS6F/ghd0goHsGWMkgihK42SR22eJH33NEjGEOAixzAjRoCxjlH7Mv5CvC+VtZyzUNZNIfxUhjV+Lf2M8LjF0U0LVjgMFmUtpeHWyP+GGra8uozxIckfhjWC5JNfMMvgzYJmL9gV9yS6HDHCy1E1yUSNhV9e11BC5KeXNsFZG6Z+AGU8MuGlY16UDAXI+arLRijZwq7sgWT6Feh6Cc7JT9CJQPjNWcswNB2UPRXctjQsV/qY3qCaO7tba5VsxC9YsGlWyNtHuezMlDPbu335VCInxILDgGuPepr344f0TnqkkKZOyrJiEgZIrjOl0YMUDJDxxxm8qeQ4EGTNbAxCQvxmrBdLRJFUe2ajniO4JRQBdmzHQ9lc+A50bVuK2PovHMo5VKwR7dcvQcmSVQVwW3t2GyrBwDRkXCXzuD5hSSFAqelnspkZcNootgF13FeL9h95nagi0r6f5SkJ2DJ2c/8O0Ib/Tps03VxQYhkZCAVQCXTEeyEeZls5g4zAgjxBM9TNUxSgUoTy9NUBZLp3Qi4vvwyftLCmsIMXbTBpga49WqaCxVUOl0T3vtnVmHdTXDQ9LOiKSLvxg0ro0iIOefHrY/yE6z/QN2phzo5seTVMZ+jTuOXqAcc8YRw18czh2u0Lmd7D+a952og==
  template:
    metadata:
      name: authservice-secret
      namespace: nextgen
