apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - postgres-sealed-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml

  - apiservice-configmap.yaml
  - apiservice-deployment.yaml
  - apiservice-service.yaml

  - authservice-configmap.yaml
  - authservice-sealed-secret.yaml
  - authservice-deployment.yaml
  - authservice-service.yaml

  - userservice-secret.yaml
  - userservice-deployment.yaml
  - userservice-service.yaml

  - frontend-deployment.yaml
  - frontend-service.yaml

  - nextgen-ingress.yaml
