apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
        - name: apiservice
          image: docker.io/suryadasari31/nextgen-apiservice:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: AUTH_SERVICE_URL
              value: http://authservice:9001
            - name: USER_SERVICE_URL
              value: http://userservice:9002

---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  selector:
    app: apiservice
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apiservice
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: apiservice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apiservice
                port:
                  number: 9000
